name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./src"
            version: "~= 22.0"
      - uses: chartboost/ruff-action@v1
        with:
            src: "./src"
            version: 0.0.279
